

        

---
- name: Deploy Scientific Calculator Docker Container
  hosts: all
  become: no
  tasks:
    - name: Pull the latest Docker Hub image
      community.docker.docker_image:
        name: "asutoshassignment/scientific-calculator"
        tag: latest
        source: pull

    - name: Stop and remove any existing calculator container
      community.docker.docker_container:
        name: scientific-calculator-app
        state: absent

    - name: Run the newly built container
      community.docker.docker_container:
        name: scientific-calculator-app
        image: "asutoshassignment/scientific-calculator:latest"
        state: started
        restart_policy: unless-stopped
        interactive: yes
        tty: yes
